name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Krav G
      id: krav-g
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Krav G
        setup-command: cd server && npm install && npx plugga mongo
        command: cd server && npx plugga test --vitest --ts --run .g.
        timeout: 10
        max-score: 60
    - name: Krav VG
      id: krav-vg
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Krav VG
        setup-command: cd server && npm install && npx plugga mongo
        command: cd server && npx plugga test --vitest --ts --run .vg.
        timeout: 10
        max-score: 40
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        KRAV-G_RESULTS: "${{steps.krav-g.outputs.result}}"
        KRAV-VG_RESULTS: "${{steps.krav-vg.outputs.result}}"
      with:
        runners: krav-g,krav-vg
